### ISSUE TITLE
SNSのコンセプト

### ISSUE THREAD

**Issue by marihachi** [Frost-Dev/Frost-Web#1]
ほかのサービスに無いような特徴を持たせたい。
案などあればください

- 投稿内容内の命令等によって音楽が流れたり

**Comment by ToMeWelcome** [comment]
モスバーガーのネット注文

**Comment by potato4d** [comment]
グローバルナビゲーションでミラーボールが回るサイト設計

**Comment by marihachi** [comment]
(・＿・)

**Comment by ToMeWelcome** [comment]
まりはちバーガーガチャ

**Comment by ToMeWelcome** [comment]
ユーザーページの実装

**Comment by potato4d** [comment]
なんか特定のハッシュタグのツイートが流れると音楽流れたり音楽変わったりしたら面白そう

**Comment by ToMeWelcome** [comment]
投稿機能の実装

**Comment by takeyari** [comment]
- 頭洗い報告
- 顔写真自動モザイク
- オフ会でトイレに行ったきり戻ってこれない奴のために位置情報共有
- タバスコをワンクリックで購入

**Comment by potato4d** [comment]
これほしいかも
> オフ会でトイレに行ったきり戻ってこれない奴のために位置情報共有

**Comment by marihachi** [comment]
@potato4d いいねそれ

**Comment by otofune** [comment]
投稿に概略を付けられる

**Comment by ToMeWelcome** [comment]
Frostサーバーに自動で自らDos攻撃をする

**Comment by takeyari** [comment]
なんでそんな長文投稿する必要があるんですか

**Comment by otofune** [comment]
長文投稿したいじゃんアゼルバイジャン

**Comment by potato4d** [comment]
GithubのIssueと連携して投稿できる機能

**Comment by ToMeWelcome** [comment]
動画投稿機能

**Comment by takeyari** [comment]
動画、いいけどリソースがヤバそう

**Comment by ToMeWelcome** [comment]
背景画像

**Comment by ToMeWelcome** [comment]
イメージキャラ

**Comment by marihachi** [comment]
「チャンネル」というタイムラインの単位で作成・削除ができるようにして、
画面上にいくつかのチャンネルを並べられるようにするとかどうですか

**Comment by potato4d** [comment]
いいっすね

**Comment by otofune** [comment]
Slackかな

**Comment by potato4d** [comment]
Slackより行ったり来たりする必要が無いのはいい

**Comment by ToMeWelcome** [comment]
チャンネル作らなくてもハッシュタグをTweetdeck風に並べれば良くね

**Comment by ToMeWelcome** [comment]
実装が面倒そう

**Comment by potato4d** [comment]
それナガシミなのでは！？

**Comment by marihachi** [comment]
んでチャンネルの削除はユーザーがそのチャンネルから１人もいなくなったら自動消滅するとか

**Comment by otofune** [comment]
あら便利

**Comment by ToMeWelcome** [comment]
チャンネルは実装も使いこなしも面倒そう

**Comment by otofune** [comment]
ただ見渡しづらくなりそうだというのはある

**Comment by marihachi** [comment]
そうかな？

**Comment by potato4d** [comment]
雰囲気としてはSNSっていうよりチャットルームっぽくなりそうだね

**Comment by ToMeWelcome** [comment]
ハッシュタグ別表示。。。

**Comment by marihachi** [comment]
ダメだチャットルームにしかならない

**Comment by ToMeWelcome** [comment]
それか投稿欄は一つでもハッシュタグつけた投稿はTLから見えずにプロフィールページかハッシュタグページでしか見れないようにするのは

**Comment by marihachi** [comment]
なるほどね

**Comment by potato4d** [comment]
チャンネルをtmuxみたいに使えたら楽しそう（SNSとしてどうかは別で触ってて楽しそう）

**Comment by ToMeWelcome** [comment]
SNSと考えるのを止めよう(提案)

**Comment by marihachi** [comment]
完全にチャットサービスな件

**Comment by ToMeWelcome** [comment]
Frost Botの導入

**Comment by marihachi** [comment]
チャンネルごとに鍵をかけられるようにして、そのチャンネル内の権限ユーザーによる承認で参加とか

**Comment by ToMeWelcome** [comment]
Sl○ck Botみたいに

**Comment by marihachi** [comment]
初期のホームチャンネルは公開として、ユーザーページには公開チャンネルの投稿だけ(もしくはユーザーが参照可能なチャンネルを含む投稿)が表示されるとか

**Comment by marihachi** [comment]
Sl○ckって知らない

**Comment by Petitsurume** [comment]
これ個別にIssue建てるべきでは
