### ISSUE TITLE
動作させるための手順とコンフィグファイルの形式公開

### ISSUE THREAD

**Issue by otofune** [Frost-Dev/Frost-Web#2]

**Comment by otofune** [comment]
#10 にするためにも

**Comment by marihachi** [comment]
ハイ..

**Comment by marihachi** [comment]
Web側もNodeで動かすようにするんでその際にでも

**Comment by Petitsurume** [comment]
dockerでどっかーんしようぜ

**Comment by marihachi** [comment]
やり方よくわかんないし分かる人やってほしい

**Comment by Asteriskx** [comment]
docker とは…(´･_･`)？

**Comment by marihachi** [comment]
どっかーん！

**Comment by otofune** [comment]
dockerというのは設定ファイルから1発で設定されたとおりの環境が仮想的に構築できるソフトウエアだよ

**Comment by marihachi** [comment]
設定ファイル公開するようにしました
https://github.com/Frost-Dev/Frost/blob/master/config.json

セットアップの手順はまたそのうち

**Comment by marihachi** [comment]
しました
