### ISSUE TITLE
CSSフレームワークを使う

### ISSUE THREAD

**Issue by otofune** [Frost-Dev/Frost-Web#9]
楽になりそう
http://getskeleton.com/ とか https://purecss.io/ とか http://websymphony.net/almost-flat-ui/ とか http://kathamo.github.io/ とか

**Comment by marihachi** [comment]
使うのもあり

**Comment by marihachi** [comment]
getskeletonすきかも

**Comment by marihachi** [comment]
涼しさを感じるし候補としてはそれかなあ

**Comment by otofune** [comment]
Skeletonの見た目好きなんだよね

**Comment by marihachi** [comment]
暫定的にSkeleton使っていくことにします
